language: python
env:
  global:
  - AWS_DEFAULT_REGION: us-east-1
install:
- pip install awscli
script:
- "./util/recache"
- "./util/test"
- sudo mv /usr/bin/gpg /usr/bin/gpg.bak
- which gpg || echo "Testing without GPG"
- "./util/test"
- sudo mv $(which curl) $(which curl).bak
- which curl || echo "Testing without curl"
- "./util/test"
