language: python
env:
  global:
  - AWS_DEFAULT_REGION: us-east-1
  - AWS_ACCESS_KEY_ID: AKIAIILUOETJNPSU3JCQ
  - secure: flkzIvTIXqQ/ZsHjiFNujD6Bf2fITH/hkScAhRfYsgCElstfQdpiUKAzEUgnTXPgcjxxGwREs1ZYBuH15J3E3GhLv6MPjHdXBMNZZVtqoVbgXqPNKe8LKVuSxXIsOJar1JdEHMpkZtrWMOIFdY61D5l3+/87o+s6YNQpAN8IADQ=
install:
- pip install awscli
script:
- "./util/recache"
- "./util/test"
- sudo mv /usr/bin/gpg /usr/bin/gpg.bak
- which gpg || echo "Testing without GPG"
- "./util/test"
